#!/bin/bash
###########- BOT TELE ################
AKUN="AKUN TROJAN"
TIMES="10"
CHATID="5627481033"
KEY="5684804886:AAFup0F9eqNPL7yIUUmTPE5is2SaAIYZixQ"
URL="https://api.telegram.org/bot$KEY/sendMessage"
##################### END BOT TELE ###############

source /var/lib/alexxa-pro/ipvps.conf
domain=$(cat /etc/xray/domain)
echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
echo -e "$COLOR1 ${NC} ${COLBG1}           • CREATE TROJAN USER •              ${NC} $COLOR1 $NC"
echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"
echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
tr="$(cat ~/log-install.txt | grep -w "Trojan WS " | cut -d: -f2|sed 's/ //g')"
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${user_EXISTS} == '0' ]]; do
read -rp "   Input Username : " -e user
OWNER="WEBTROJAN"
CHATIDGC="-958733342"
if [ -z $user ]; then
echo -e "$COLOR1 ${NC}   [Error] Username cannot be empty "
echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}" 
echo -e "$COLOR1┌────────────────────── BY ───────────────────────┐${NC}"
echo -e "$COLOR1 ${NC}                • HayoSia Store •                 $COLOR1 $NC"
echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"
echo ""
read -n 1 -s -r -p "   Press any key to back on menu"
menu
fi
user_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)
if [[ ${user_EXISTS} == '1' ]]; then
clear
echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
echo -e "$COLOR1 ${NC} ${COLBG1}           • CREATE TROJAN USER •              ${NC} $COLOR1 $NC"
echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"
echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
echo -e "$COLOR1 ${NC}  Please choose another name."
echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}" 
echo -e "$COLOR1┌────────────────────── BY ───────────────────────┐${NC}"
echo -e "$COLOR1 ${NC}                • HayoSia Store •                 $COLOR1 $NC"
echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"
read -n 1 -s -r -p "   Press any key to back on menu"
trojan-menu
fi
done
uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "   Expired : " masaaktif
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
systemctl restart xray
trojanlink1="trojan://${uuid}@${domain}:${tr}?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=bug.com#${user}"
trojanlink="trojan://${uuid}@${domain}:${tr}?path=%2Ftrojan-ws&security=tls&host=bug.com&type=ws&sni=bug.com#${user}"
cat > /home/vps/public_html/trojan-$user.txt <<-END
=============================
I N F O              A K U N
=============================
Remarks     : $user
Expired On  : $exp
Host/IP     : $domain 
Port        : $tr
User ID     : $uuid
AlterId     : 0
Security    : auto
Network     : WS or gRPC
Path        : /trojan-ws
Path WSS    : wss://hayosia/trojan-ws
ServiceName : trojan-grpc
=============================
Link WS : $trojanlink
=============================
Link GRPC : $trojanlink1
=============================
END

TRX="
<code>INFO MASKU -Transaksi</code>
<code>────────────────────</code>
<b>  ⚠️TRANSAKSI TROJAN WS⚠️      </b>
<code>────────────────────</code>
<code>🌟Owner   : $OWNER</code>
<code>🌟Detail  : $AKUN</code>
<code>🌟Durasi  : $exp</code>
<code>🌟Server  : $domain</code>
<code>────────────────────</code>
<i>Notifikasi Via DeadrzBOT</i>
<b>Tele : @ProjectDedi_bot</b>
"
TEXT="
<code>──────────────────────────</code>
<code>   ⚠️Trojan Account</code>⚠️
<code>──────────────────────────</code>
<code>💥Remarks      : </code><code>$user</code>
<code>💥Domain       : </code><code>$domain</code>
<code>💥Port         : </code><code>$tr</code>
<code>💥User ID      : </code><code>$uuid</code>
<code>💥AlterId      : 0</code>
<code>💥Security     : auto</code>
<code>💥Network      : WS or gRPC</code>
<code>💥Path         : </code><code>/trojan-ws</code>
<code>💥Path WSS     : </code><code>wss://hayosia/trojan-ws</code>
<code>💥ServiceName  : </code><code>trojan-grpc</code>
<code>──────────────────────────</code>
<code>🔮 Details INFO :</code>
http://${domain}:81/trojan-$user.txt
<code>️📅 Expired On : $exp</code>
<code>──────────────────────────</code>
<i>Notifikasi Via DeadrzBOT</i>
<b>Tele : @ProjectDedi_bot</b>
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL
clear
curl -s --max-time $TIMES -d "chat_id=$CHATIDGC&disable_web_page_preview=1&text=$TRX&parse_mode=html" $URL

clear
echo -e "$COLOR1─────────────────────────────────────────────────${NC}"
echo -e "$COLOR1 ${NC} ${COLBG1}           • CREATE TROJAN USER •             ${NC} $COLOR1 $NC"
echo -e "$COLOR1─────────────────────────────────────────────────${NC}"
echo -e "$COLOR1─────────────────────────────────────────────────${NC}"
echo -e "$COLOR1 ${NC} Remarks     : ${user}" 
echo -e "$COLOR1 ${NC} Expired On  : $exp" 
echo -e "$COLOR1 ${NC} Host/IP     : ${domain}" 
echo -e "$COLOR1 ${NC} Port        : ${tr}" 
echo -e "$COLOR1 ${NC} Key         : ${uuid}" 
echo -e "$COLOR1 ${NC} Path        : /trojan-ws"
echo -e "$COLOR1 ${NC} Path WSS    : wss://hayosia/trojan-ws" 
echo -e "$COLOR1 ${NC} ServiceName : trojan-grpc" 
echo -e "$COLOR1─────────────────────────────────────────────────${NC}" 
echo -e "$COLOR1─────────────────────────────────────────────────${NC}"
echo -e "$COLOR1 ${NC} Link WS : "
echo -e "$COLOR1 ${NC} ${trojanlink}" 
echo -e "$COLOR1 ${NC} "
echo -e "$COLOR1 ${NC} Link GRPC : "
echo -e "$COLOR1 ${NC} ${trojanlink1}"
echo -e "$COLOR1─────────────────────────────────────────────────${NC}" 
echo -e "$COLOR1────────────────────── BY ───────────────────────${NC}"
echo -e "$COLOR1 ${NC}                • HayoSia Store •                 $COLOR1 $NC"
echo -e "$COLOR1─────────────────────────────────────────────────${NC}"
echo "" 
#read -n 1 -s -r -p "   Press any key to back on menu"
#menu-trojan
